const colDefs: ColDef<TransactionPw>[] = [
  {
    field: 'id',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.id.label,
    headerTooltip: 'id',
  },
  {
    field: 'dr_value_date',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.dr_value_date.label,
    headerTooltip: 'dr_value_date',
  },
  {
    field: 'contract_ref_no',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.contract_ref_no.label,
    headerTooltip: 'contract_ref_no',
  },
  {
    field: 'lcy_equivalent',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.lcy_equivalent.label,
    headerTooltip: 'lcy_equivalent',
  },
  {
    field: 'txn_ccy',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.txn_ccy.label,
    headerTooltip: 'txn_ccy',
  },
  {
    field: 'txn_amount',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.txn_amount.label,
    headerTooltip: 'txn_amount',
  },
  {
    field: 'exch_rate',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.exch_rate.label,
    headerTooltip: 'exch_rate',
  },
  {
    field: 'department_code',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.department_code.label,
    headerTooltip: 'department_code',
  },
  {
    field: 'transfer_type',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.transfer_type.label,
    headerTooltip: 'transfer_type',
  },
  {
    field: 'dr_ac_brn',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.dr_ac_brn.label,
    headerTooltip: 'dr_ac_brn',
  },
  {
    field: 'dr_account',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.dr_account.label,
    headerTooltip: 'dr_account',
  },
  {
    field: 'dr_ac_ccy',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.dr_ac_ccy.label,
    headerTooltip: 'dr_ac_ccy',
  },
  {
    field: 'dr_amount',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.dr_amount.label,
    headerTooltip: 'dr_amount',
  },
  {
    field: 'cr_ac_brn',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.cr_ac_brn.label,
    headerTooltip: 'cr_ac_brn',
  },
  {
    field: 'cr_ac_no',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.cr_ac_no.label,
    headerTooltip: 'cr_ac_no',
  },
  {
    field: 'cr_ac_ccy',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.cr_ac_ccy.label,
    headerTooltip: 'cr_ac_ccy',
  },
  {
    field: 'cr_amount',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.cr_amount.label,
    headerTooltip: 'cr_amount',
  },
  {
    field: 'payment_type',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.payment_type.label,
    headerTooltip: 'payment_type',
  },
  {
    field: 'account_class_cr',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.account_class_cr.label,
    headerTooltip: 'account_class_cr',
  },
  {
    field: 'network_code',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.network_code.label,
    headerTooltip: 'network_code',
  },
  {
    field: 'product_code',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.product_code.label,
    headerTooltip: 'product_code',
  },
  {
    field: 'source_code',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.source_code.label,
    headerTooltip: 'source_code',
  },
  {
    field: 'customer_category_cr',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.customer_category_cr.label,
    headerTooltip: 'customer_category_cr',
  },
  {
    field: 'gfcid_cr',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.gfcid_cr.label,
    headerTooltip: 'gfcid_cr',
  },
  {
    field: 'beneficiary1',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.beneficiary1.label,
    headerTooltip: 'beneficiary1',
  },
  {
    field: 'beneficiary2',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.beneficiary2.label,
    headerTooltip: 'beneficiary2',
  },
  {
    field: 'beneficiary3',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.beneficiary3.label,
    headerTooltip: 'beneficiary3',
  },
  {
    field: 'beneficiary5',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.beneficiary5.label,
    headerTooltip: 'beneficiary5',
  },
  {
    field: 'ordering_customer1',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.ordering_customer1.label,
    headerTooltip: 'ordering_customer1',
  },
  {
    field: 'ordering_customer2',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.ordering_customer2.label,
    headerTooltip: 'ordering_customer2',
  },
  {
    field: 'ordering_customer3',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.ordering_customer3.label,
    headerTooltip: 'ordering_customer3',
  },
  {
    field: 'sndr_to_rcvr_info1',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.sndr_to_rcvr_info1.label,
    headerTooltip: 'sndr_to_rcvr_info1',
  },
  {
    field: 'sndr_to_rcvr_info2',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.sndr_to_rcvr_info2.label,
    headerTooltip: 'sndr_to_rcvr_info2',
  },
  {
    field: 'sndr_to_rcvr_info3',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.sndr_to_rcvr_info3.label,
    headerTooltip: 'sndr_to_rcvr_info3',
  },
  {
    field: 'sndr_to_rcvr_info4',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.sndr_to_rcvr_info4.label,
    headerTooltip: 'sndr_to_rcvr_info4',
  },
  {
    field: 'country_out',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.country_out.label,
    headerTooltip: 'country_out',
  },
  {
    field: 'transfer_in',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.transfer_in.label,
    headerTooltip: 'transfer_in',
  },
  {
    field: 'trn_desc',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.trn_desc.label,
    headerTooltip: 'trn_desc',
  },
  {
    field: 'trn_code',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.trn_code.label,
    headerTooltip: 'trn_code',
  },
  {
    field: 'drcr_ind',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.drcr_ind.label,
    headerTooltip: 'drcr_ind',
  },
  {
    field: 'payment_details1',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.payment_details1.label,
    headerTooltip: 'payment_details1',
  },
  {
    field: 'payment_details2',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.payment_details2.label,
    headerTooltip: 'payment_details2',
  },
  {
    field: 'payment_details3',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.payment_details3.label,
    headerTooltip: 'payment_details3',
  },
  {
    field: 'payment_details4',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.payment_details4.label,
    headerTooltip: 'payment_details4',
  },
  {
    field: 'trans_mode',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.trans_mode.label,
    headerTooltip: 'trans_mode',
  },
  {
    field: 'txn_init_date',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.txn_init_date.label,
    headerTooltip: 'txn_init_date',
  },
  {
    field: 'transaction_id',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.transaction_id.label,
    headerTooltip: 'transaction_id',
  },
  {
    field: 'addressfree',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.addressfree.label,
    headerTooltip: 'addressfree',
  },
  {
    field: 'addr_street',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.addr_street.label,
    headerTooltip: 'addr_street',
  },
  {
    field: 'addr_town',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.addr_town.label,
    headerTooltip: 'addr_town',
  },
  {
    field: 'addr_country_code',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.addr_country_code.label,
    headerTooltip: 'addr_country_code',
  },
  {
    field: 'trans_type',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.trans_type.label,
    headerTooltip: 'trans_type',
  },
  {
    field: 't_from',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.t_from.label,
    headerTooltip: 't_from',
  },
  {
    field: 't_to_my_client',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.t_to_my_client.label,
    headerTooltip: 't_to_my_client',
  },
  {
    field: 'from_account',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.from_account.label,
    headerTooltip: 'from_account',
  },
  {
    field: 'to_account',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.to_account.label,
    headerTooltip: 'to_account',
  },
  {
    field: 'from_subject_to_subject',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.from_subject_to_subject.label,
    headerTooltip: 'from_subject_to_subject',
  },
  {
    field: 'source_system',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.source_system.label,
    headerTooltip: 'source_system',
  },
  {
    field: 'record_status',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.record_status.label,
    headerTooltip: 'record_status',
  },
  {
    field: 'version_no',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.version_no.label,
    headerTooltip: 'version_no',
  },
  {
    field: 'created_on',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.created_on.label,
    headerTooltip: 'created_on',
  },
  {
    field: 'created_by',
    width: 200,
    headerName: TRANSACTION_PW_FIELDS.created_by.label,
    headerTooltip: 'created_by',
  },
];
